Increase retry backoff RHELDST-9957
release-engineering/pubtools-pulp pull request #154
Opened 2022-07-25 10:33 UTC by amcmahon-rh

Several tasks have failed to flush the UD Cache, for both repo and errata data types. Previous investigations pointed to an issue with the /internal/rcm/flush-cache endpoint, which is an API managed by teamnado. Teamnado folks have said the host running this endpoint has had some issues. Between this info, the fact that the task can succeed when retried later and the exceptions that occur, I believe the intermittent host unavailability is the root issue.

This PR duplicates the same changes I made in pub-utils, increasing the total duration over which retries are carried out. If the root cause of failures is due to intermittent outages, extending the waiting time between retries should allow the issue to pass.

2022-07-25 13:20 UTC, amcmahon-rh commented
For some reason the rpm-py-installer package no longer works with python3.8. I'm looking into it atm

2022-07-26 03:40 UTC, rohanpm requested changes

2022-07-26 03:40 UTC, rohanpm commented on tox.ini
> +[testenv:py38]
I guess you've added this for debugging the CI failure relating to rpm-py-installer.  Could you drop it now please?  That problem has disappeared.

2022-07-27 04:53 UTC, rohanpm approved these changes

2022-07-27 16:24 UTC, rajulkumar approved these changes

2022-07-27 16:29 UTC, merged